"""initial schema: filings, queries, citations

Revision ID: 8e3d61e26122
Revises: 
Create Date: 2026-08-10 11:38:14.323661

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8e3d61e26122'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('filings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('cik', sa.String(length=10), nullable=False),
    sa.Column('ticker', sa.String(length=10), nullable=True),
    sa.Column('company_name', sa.String(length=255), nullable=False),
    sa.Column('form_type', sa.String(length=10), nullable=False),
    sa.Column('accession_number', sa.String(length=25), nullable=False),
    sa.Column('filing_date', sa.Date(), nullable=False),
    sa.Column('fiscal_year', sa.Integer(), nullable=False),
    sa.Column('fiscal_period', sa.String(length=4), nullable=True),
    sa.Column('source_url', sa.Text(), nullable=False),
    sa.Column('storage_key', sa.Text(), nullable=True),
    sa.Column('chunk_count', sa.Integer(), nullable=False),
    sa.Column('ingested_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('accession_number', name='uq_filings_accession')
    )
    op.create_index(op.f('ix_filings_cik'), 'filings', ['cik'], unique=False)
    op.create_index(op.f('ix_filings_fiscal_year'), 'filings', ['fiscal_year'], unique=False)
    op.create_index(op.f('ix_filings_form_type'), 'filings', ['form_type'], unique=False)
    op.create_index(op.f('ix_filings_ticker'), 'filings', ['ticker'], unique=False)
    op.create_table('queries',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('question', sa.Text(), nullable=False),
    sa.Column('answer', sa.Text(), nullable=False),
    sa.Column('model', sa.String(length=64), nullable=True),
    sa.Column('retrieval_mode', sa.String(length=16), nullable=False),
    sa.Column('top_k', sa.Integer(), nullable=False),
    sa.Column('filters', sa.JSON(), nullable=True),
    sa.Column('is_grounded', sa.Boolean(), nullable=False),
    sa.Column('ungrounded_figures', sa.JSON(), nullable=True),
    sa.Column('latency_ms', sa.Float(), nullable=True),
    sa.Column('input_tokens', sa.Integer(), nullable=True),
    sa.Column('output_tokens', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_queries_created_at'), 'queries', ['created_at'], unique=False)
    op.create_index(op.f('ix_queries_is_grounded'), 'queries', ['is_grounded'], unique=False)
    op.create_table('citations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('query_id', sa.Integer(), nullable=False),
    sa.Column('chunk_id', sa.String(length=128), nullable=False),
    sa.Column('citation', sa.String(length=64), nullable=False),
    sa.Column('excerpt', sa.Text(), nullable=False),
    sa.Column('rank', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['query_id'], ['queries.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_citations_citation'), 'citations', ['citation'], unique=False)
    op.create_index(op.f('ix_citations_query_id'), 'citations', ['query_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_citations_query_id'), table_name='citations')
    op.drop_index(op.f('ix_citations_citation'), table_name='citations')
    op.drop_table('citations')
    op.drop_index(op.f('ix_queries_is_grounded'), table_name='queries')
    op.drop_index(op.f('ix_queries_created_at'), table_name='queries')
    op.drop_table('queries')
    op.drop_index(op.f('ix_filings_ticker'), table_name='filings')
    op.drop_index(op.f('ix_filings_form_type'), table_name='filings')
    op.drop_index(op.f('ix_filings_fiscal_year'), table_name='filings')
    op.drop_index(op.f('ix_filings_cik'), table_name='filings')
    op.drop_table('filings')
    # ### end Alembic commands ###
